import joblib
import numpy as np
from pathlib import Path
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Initialize the FastAPI application for NeuroSentry
app = FastAPI(title="NeuroSentry Inference API", version="1.0")

# Configure CORS to allow the Next.js frontend to communicate securely
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],  # Allows your local Next.js server
    allow_credentials=True,
    allow_methods=["*"],  # Allows POST, GET, OPTIONS, etc.
    allow_headers=["*"],
)

# Safely load the ML Model and metadata generated by train_pipeline.py
try:
    model_path = Path(__file__).resolve().parent / "stress_risk_model.joblib"
    payload = joblib.load(model_path)
    model = payload["model"]
    features = payload["features"]
    risk_labels = payload["risk_labels"]
except FileNotFoundError:
    raise RuntimeError(f"Model file not found at '{model_path}'. Ensure stress_risk_model.joblib is deployed with app.py.")

# Define the exact JSON Data Contract expected from the frontend
class PersonnelVitals(BaseModel):
    personnel_id: str = Field(default="CAPF_1042")
    consecutive_duty_days: int = Field(..., ge=1, le=120)
    leave_denials_past_year: int = Field(..., ge=0, le=10)
    night_shifts_last_month: int = Field(..., ge=0, le=31)
    post_trauma_exposure: int = Field(..., ge=0, le=1)
    resting_hr: float = Field(..., ge=40, le=160)
    hrv_rmssd: float = Field(..., ge=10, le=100)
    self_reported_fatigue: int = Field(..., ge=1, le=10)

def get_intervention_recommendation(tier: int) -> str:
    """Provides actionable, defense-grade medical recommendations based on risk tier."""
    interventions = {
        0: "Maintain standard operational duties. Regular wellness checkups.",
        1: "Recommend non-strenuous secondary tasks and hydration/sleep hygiene protocol.",
        2: "Trigger mandatory medical officer interview and 48-hour operational rest rotation.",
        3: "Immediate clinical psychological evaluation required. Workload detachment authorized."
    }
    return interventions.get(tier, "Review by Welfare Officer.")

@app.post("/api/v1/predict")
def predict_stress_risk(vitals: PersonnelVitals):
    try:
        # Transform incoming JSON into the exact numpy array structure the model expects
        input_vector = np.array([[
            vitals.consecutive_duty_days,
            vitals.leave_denials_past_year,
            vitals.night_shifts_last_month,
            vitals.post_trauma_exposure,
            vitals.resting_hr,
            vitals.hrv_rmssd,
            vitals.self_reported_fatigue
        ]])
        
        # Execute ML inference
        probs = model.predict_proba(input_vector)[0]
        predicted_tier = int(np.argmax(probs))
        confidence = float(probs[predicted_tier])
        
        # Explainable AI (XAI): Calculate which feature caused the alert
        importances = model.feature_importances_
        primary_factor_idx = int(np.argmax(importances))
        primary_stressor = features[primary_factor_idx].replace('_', ' ').title()

        return {
            "personnel_id": vitals.personnel_id,
            "risk_tier": predicted_tier,
            "risk_label": risk_labels[predicted_tier],
            "confidence_score": round(confidence, 4),
            "primary_trigger": primary_stressor,
            "recommended_intervention": get_intervention_recommendation(predicted_tier)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Inference Engine Error: {str(e)}")

@app.get("/health")
def health_check():
    return {"status": "Operational", "service": "NeuroSentry ML Engine"}